af:
  main_1_0: 0
  marketing: 0
  server: 0
an:
  main_1_0: 12
  marketing: 0
  server: 24
ar:
  main_1_0: 55
  marketing: 0
  server: 41
be-BY:
  main_1_0: 15
  marketing: 0
  server: 44
bg-BG:
  main_1_0: 8
  marketing: 0
  server: 6
ca:
  main_1_0: 63
  marketing: 62
  server: 44
cmn:
  main_1_0: 5
  marketing: 0
  server: 3
cs:
  main_1_0: 41
  marketing: 2
  server: 31
da:
  main_1_0: 18
  marketing: 0
  server: 24
de:
  main_1_0: 63
  marketing: 0
  server: 44
el:
  main_1_0: 26
  marketing: 0
  server: 35
en-BE:
  main_1_0: 0
  marketing: 0
  server: 0
en-NL:
  main_1_0: 0
  marketing: 0
  server: 0
en-US: {}
eo:
  main_1_0: 14
  marketing: 0
  server: 24
es:
  main_1_0: 81
  marketing: 100
  server: 80
es-AR:
  main_1_0: 0
  marketing: 0
  server: 0
fa-IR:
  main_1_0: 1
  marketing: 0
  server: 2
fi:
  main_1_0: 8
  marketing: 0
  server: 4
fr:
  main_1_0: 81
  marketing: 100
  server: 80
fr-BE:
  main_1_0: 0
  marketing: 0
  server: 0
ga-IE:
  main_1_0: 53
  marketing: 2
  server: 24
gl:
  main_1_0: 9
  marketing: 0
  server: 11
he:
  main_1_0: 7
  marketing: 0
  server: 12
he-IL: {}
hi:
  main_1_0: 0
  marketing: 0
  server: 0
hi-IN: {}
hr:
  main_1_0: 4
  marketing: 0
  server: 3
hu:
  main_1_0: 29
  marketing: 0
  server: 30
id:
  main_1_0: 10
  marketing: 0
  server: 13
io:
  main_1_0: 0
  marketing: 0
  server: 0
it:
  main_1_0: 42
  marketing: 0
  server: 39
it-CH:
  main_1_0: 0
  marketing: 0
  server: 0
it-IT: {}
ja:
  main_1_0: 12
  marketing: 0
  server: 18
km:
  main_1_0: 9
  marketing: 0
  server: 13
ko:
  main_1_0: 69
  marketing: 45
  server: 23
ko-KR: {}
lt:
  main_1_0: 20
  marketing: 6
  server: 5
lv:
  main_1_0: 0
  marketing: 0
  server: 0
mi:
  main_1_0: 6
  marketing: 1
  server: 1
mk:
  main_1_0: 8
  marketing: 0
  server: 16
ml:
  main_1_0: 9
  marketing: 0
  server: 13
ml-IN:
  main_1_0: 0
  marketing: 0
  server: 0
nb-NO:
  main_1_0: 0
  marketing: 0
  server: 0
nl: {}
nl-NL:
  main_1_0: 85
  marketing: 100
  server: 84
pl:
  main_1_0: 31
  marketing: 0
  server: 13
pt-BR:
  main_1_0: 81
  marketing: 100
  server: 80
pt-PT:
  main_1_0: 0
  marketing: 0
  server: 1
ro:
  main_1_0: 26
  marketing: 0
  server: 34
ru:
  main_1_0: 31
  marketing: 2
  server: 10
ru-RU: {}
sk:
  main_1_0: 12
  marketing: 0
  server: 24
sl:
  main_1_0: 15
  marketing: 0
  server: 27
sr:
  main_1_0: 66
  marketing: 81
  server: 69
sr-RS:
  main_1_0: 22
  marketing: 0
  server: 39
sv:
  main_1_0: 19
  marketing: 68
  server: 26
te:
  main_1_0: 6
  marketing: 0
  server: 7
te-IN: {}
th: {}
th-TH:
  main_1_0: 0
  marketing: 0
  server: 0
tr:
  main_1_0: 52
  marketing: 0
  server: 41
uk:
  main_1_0: 81
  marketing: 5
  server: 27
ur:
  main_1_0: 0
  marketing: 0
  server: 0
ur-PK:
  main_1_0: 0
  marketing: 0
  server: 0
vi:
  main_1_0: 8
  marketing: 0
  server: 8
zh-TW:
  main_1_0: 100
  marketing: 100
  server: 100
