loomio_webhooks:
  repo:         loomio/loomio_webhooks

loomio_tags:
  repo:         loomio/loomio_tags
  # experimental: true

loomio_truncate_comment:
  repo:         loomio/loomio_truncate_comment
  experimental: true

# loomio_onboarding:
#   repo:         loomio/loomio_onboarding

loomio_content_preview:
  repo:         piratas-ar/loomio_content_preview
  version:      piratas-ng
