loomio_webhooks:
  repo:         loomio/loomio_webhooks

loomio_tags:
  repo:         loomio/loomio_tags
  experimental: true

loomio_truncate_comment:
  repo:         loomio/loomio_truncate_comment
  experimental: true
