# To customize periods and limits, simply add period or limit to the model's configuration, like so:
#
# group_creation:
#   route: (GROUP_ROUTE_REGEX)
#   period: 10
#   limit: 5
# (don't allow more than 5 group creations per 10 seconds)

# Methods will default to POST (usually used for object creation)
# to specify a different route, just add the 'method' key:
#
# group_visit:
#   route: (GROUP_ROUTE_REGEX)
#   method: GET
#   period: 60
#   limit: 5
# (don't allow more than 5 visits to a discussion per minute)
#
# NB: period is measured in seconds; (eg period: 120 = X requests per 2 minutes)

ahoy_event_minute:
  period: 60
  limit: 60
  path: ^\/ahoy\/events$
  method: POST

default:
  period: 60
  limit: 10
  method: POST
